title: LIA+ Sistemas Embarcados e IoT
description: Frente de pesquisa em Inteligência Artificial na borda (Edge AI), Internet das Coisas (IoT) e Sensoriamento.
remote_theme: pages-themes/cayman
show_downloads: false
