title: LIA+ Engenharia de Sistemas Inteligentes
description: Arquitetura de software e hardware, IA na borda (Edge AI), IoT e integração de dados para sistemas complexos.
remote_theme: pages-themes/cayman
show_downloads: false
